[build]
publish = "exampleSite/public"
command = "hugo --gc -s exampleSite --minify"

[context.production.environment]
HUGO_VERSION = "0.109.0"

[context.deploy-preview]
command = "hugo -s exampleSite --minify -D -F -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.109.0"

[context.branch-deploy]
command = "hugo -s exampleSite --minify --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.109.0"

[[redirects]]
from = "/"
to = "/logged"
force = true
status = 302
conditions = {Role = ["user"]}

[[redirects]]
from = "/logged/*"
to = "/:splat"
force = true
status = 302